### ISSUE TITLE
TypeScript conversion breaks ember-cli@3.9.0-beta.2+

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/resolve-package-path#11]
Basically this pattern:

```ts
exports = Foo
function Foo() {}

module.exports.blah = function() {};
```

Results in the following transpilation:

```js
module.exports.blah = function() {};

module.exports = Foo;
```

As a result `getRealDirectoryPath` and `getRealFilePath` are not available as exports.

---

This is the root cause of https://github.com/ember-cli/ember-cli/issues/8483.

**Comment by stefanpenner** [comment]
Oops. I need to add some additional smoke tests.

Sorry this TS conversation ended up being a shit show.
