### ISSUE TITLE
Missing CHANGELOG

### ISSUE THREAD

**Issue by Turbo87** [stefanpenner/resolve-package-path#15]
Apparently, there have been [18 releases](https://github.com/stefanpenner/resolve-package-path/releases) so far, but it's not clear what has changed between them.

**Comment by stefanpenner** [comment]
This project does not have a changelog. I would accept a PR introducing tooling to create one, but at this time we do not offer this.

**Comment by Turbo87** [comment]
```
npx lerna-changelog
```

(see https://github.com/lerna/lerna-changelog)

it would require you to assign labels to the merged PRs though so that it can categorize the PRs properly.
