### ISSUE TITLE
Y U NO CHANGELOG?! 😭😆🙏

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/resolve-package-path#30]
Would you like me to setup a release automation setup for this project that will allow us to generate a nice changelog (assuming we follow the steps)?

`npx create-rwjblue-release-it-setup`

**Comment by andi1984** [comment]
I agree a changelog would be nice

**Comment by stefanpenner** [comment]
@rwjblue as a wise man (@rwjblue)  once said, PRs welcome :trollface:

**Comment by stefanpenner** [comment]
Changelog started with the 4x release: https://github.com/stefanpenner/resolve-package-path/commit/80e3c48404462b1f5323598a8b5dfc7cf9eec4ec
