### ISSUE TITLE
Please publish a proper npm package

### ISSUE THREAD

**Issue by mmunte-impeo** [stefanpenner/resolve-package-path#32]
nice library!

But I see the ts and js files are published alongside. this is bad practice as TSC will then prefer to use the TS files instead of precompiled JS.  But then, we run into problems since a persons TSConfig settings might be different then yours.

You see - by exposing the TS files you open a can or worms.

Please hide it completely or separate lib and src

**Comment by stefanpenner** [comment]
may be fixed with https://github.com/stefanpenner/resolve-package-path/pull/38

**Comment by mmunte-impeo** [comment]
I will have a look and let you know. Many thx!
