### ISSUE TITLE
Broken when used with typescript 4.2

### ISSUE THREAD

**Issue by zenwarr** [stefanpenner/resolve-package-path#34]
The package cannot be used with typescript 4.2 due to the following error:

```
Error: node_modules/resolve-package-path/lib/cache.ts:16:1 - error TS4094: Property '_store' of exported class expression may not be private or protected.

 16 export = class Cache {
    ~~~~~~~~~~~~~~~~~~~~~~
 17   private _store: { [key: string]: string };
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
 40   }
    ~~~
 41 };
    ~~
```

The problem is caused by the fact that source `.ts` files are published on npm alongside with generated sources and `.d.ts` files. Related to #32

**Comment by stefanpenner** [comment]
may be fixed with https://github.com/stefanpenner/resolve-package-path/pull/38
